package com.example.hazir_mesajlar_seninle;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FakeData {

    private static final Map<String, List<String>> messagesMap = new HashMap<>();

    static {
        messagesMap.put("Tebrik", Arrays.asList("Tebrikler! Harika bir iş çıkardın.🎉",
                "Başarıların daim olsun!🏆 ",
                "Kutlarım, çok güzel bir işe imza attın.👏",
                "Bu başarı senin hakkındı, tebrik ederim.🎖",
                "Emeklerinin karşılığını aldın, tebrikler!💪",
                "Yolun hep açık olsun, başarıların devamını dilerim.🚀",
                "Seni kutluyorum, gerçekten örnek alınacak bir başarı!🌟",
                "Tebrikler, hepimiz seninle gurur duyuyoruz.🎊",
                "Çabaların boşa gitmedi, kutlarım.🔥",
                "Tebrik ederim, geleceğin parlak!✨ ",
                "Başarının keyfini çıkar, tebrikler!🥳",
                "İnanılmaz bir iş çıkardın, kutlarım!💯",
                "Her zaman daha iyiye, tebrikler!📈",
                "Bu başarı tesadüf değil, tebrikler!🎯",
                "Hak ettiğin yere geldin, tebrik ederim!🏅"));
        messagesMap.put("Sevgili Mesajları", Arrays.asList("Seni her geçen gün daha çok seviyorum.💗",
                "Seninle her şey daha güzel.🌹",
                "Aşkımız her geçen gün büyüyor.💞",
                "Gözlerine baktığımda huzur buluyorum.🔥",
                "Sen benim en değerli hazinemsin.💎",
                "Kalbim sadece sana ait.❤",
                "Seninle olmak bir mucize gibi.✨",
                "Sana her şeyimi adadım.💖",
                "Gülüşünle hayat buluyorum.😊",
                "Sana olan sevgim sonsuz.🔗",
                "Seninle geçirdiğim her saniye çok değerli.⏳",
                "Aşkla kal, benimle kal.💕",
                "Sen benim tek gerçeğimsin.🔆",
                "Hayat seninle güzel.🌍",
                "Seni tanıdığım için çok şanslıyım.🍀"));
        messagesMap.put("Bayram Mesajları", Arrays.asList("Bayramın mübarek olsun!🕌",
                "Sevdiklerinle birlikte nice bayramlara.🎊",
                "Bayramın sağlık, huzur ve mutluluk getirsin.✨",
                "Bayramda gönlünüzce eğlenin!🥳",
                "Birlik ve beraberliğimiz daim olsun.🤝 ",
                "Bayramın sevdiklerinle geçsin.💖",
                "Dostlukların pekiştiği bir bayram dilerim💙.",
                "Bayram coşkusunu doyasıya yaşa.🎈",
                "Kalplerimiz bir olsun, bayramınız kutlu olsun.❤",
                "Bayramlar, sevgiyle birleştiğimiz günlerdir.🤲",
                "Sevgiyle dolu bir bayram geçirmeni dilerim.🌟",
                "Küslükler son bulsun, bayramınız mübarek olsun.💫",
                "Bayramın neşesi daim olsun.🎶",
                "Nice mutlu bayramlara!🎁",
                "Bayram tüm güzellikleriyle seni bulsun.🌸"));
        messagesMap.put("Günaydın", Arrays.asList("Günaydın! Gülümseyerek başla bu güzel güne.🌞",
                "Yeni bir gün, yeni umutlar. Günaydın!🌅",
                "Bugün her şey çok güzel olacak. Günaydın!🎉",
                "Gözlerin gibi parlayan bir sabah olsun.✨",
                "Güneşin doğuşu kadar güzel bir gün dilerim.☀",
                "Günaydın, hayırlı sabahlar!🙏",
                "Mutlu ve enerjik bir gün seninle olsun.⚡",
                "Sabahın neşesi seninle olsun.😄",
                "Bugün harika bir gün olacak!🚀",
                "Kahveni al ve gülümseyerek başla güne.☕",
                "Uyan! Yeni fırsatlar seni bekliyor.🔔",
                "Hayata tebessüm ederek uyan. Günaydın!😊",
                "Başarı dolu bir gün dilerim. Günaydın!🏆",
                "Günaydın sevgili dostum!🤗 ",
                "Her sabah bir umuttur. Günaydın!🍀"));
        messagesMap.put("Özür Mesajları", Arrays.asList("Üzgünüm, seni kırmak istemezdim.😞",
                "Beni affetmeni tüm kalbimle diliyorum.🥹",
                "Hatalıyım ve bunu kabul ediyorum. Özür dilerim.😔",
                "Kalbini kırdıysam affet, niyetim asla bu değildi.💔",
                "Sana üzüntü verdiysem çok özür dilerim.☹",
                "Yanlışımı fark ettim, özür dilerim.🤦‍♂",
                "Lütfen beni affet, sana değer veriyorum.💖",
                "Pişmanım, senden özür diliyorum.😣",
                "Sana zarar vermek istemedim, bağışla beni.🤲 ",
                "İçtenlikle üzgünüm, telafi etmek istiyorum.💬",
                "Kırgınlığına neden olduğum için üzgünüm.😟",
                "Sana böyle hissettirdiğim için üzgünüm.😞",
                "İlişkimize zarar verdiysem affet beni.💔",
                "Seninle aramızda böyle şeyler yaşandığı için çok üzgünüm.🥺",
                "Seni kaybetmek istemem, özür dilerim.😟🥺"));
        messagesMap.put("İş Mesajları", Arrays.asList("Yeni işinde başarılar dilerim!💼",
                "Toplantında başarılar!📊",
                "Çalışmalarında kolaylıklar dilerim.🎯",
                "Günün verimli geçsin!🚀",
                "Emeğin mutlaka karşılık bulacaktır.💪",
                "Harika bir iş çıkardın, tebrikler!🏆",
                "İş yerinde her şey yolunda mı❓ Başarılar!",
                "İş hayatında hep yükselmen dileğiyle.📈",
                "Yeni projende başarılar dilerim!🔬",
                "İş arkadaşlarınla uyum içinde çalışmanı dilerim.🤝",
                "Yoğun günler seni yormasın, dinlenmeyi ihmal etme.😌",
                "Mükemmel bir sunumdu, bravo!👏",
                "Hedeflerine ulaşman dileğiyle.🏅 ",
                "Motivasyonun hep yüksek olsun!⚡",
                "İşlerin rast gitsin!🍀"));
        messagesMap.put("Doğum Günü", Arrays.asList("Doğum günün kutlu olsun!🎂",
                "Nice mutlu, sağlıklı yaşlara!🎈",
                "Yeni yaşın sana huzur getirsin.🌟",
                "Tüm dileklerinin gerçekleştiği bir yıl olsun.💫",
                "Doğum günün sevgiyle dolsun!💖",
                "İyi ki doğdun, iyi ki varsın.🥳 ",
                "Yeni yaşında her şey gönlünce olsun.🎊",
                "Daha nice yıllara!🎉",
                "Pastanın üstündeki mumlar gibi ışılda!🕯",
                "Hayatının en güzel yılı olsun.✨",
                "Sevdiklerinle birlikte harika bir doğum günü geçirmeni dilerim.🤗",
                "Yaş aldıkça güzelleşiyorsun.💃",
                "Mutluluk ve sağlıkla dolu yıllar dilerim.🍀",
                "Her günün doğum günün gibi özel olsun.🎁 ",
                "Kutlamaların bol olsun!🎶"));
        messagesMap.put("Yeni Yıl", Arrays.asList("Mutlu yıllar!🎊 ",
                "Yeni yılın sağlık, mutluluk ve başarı getirsin.🎆",
                "2025 yılı senin yılın olsun!🚀",
                "Yeni yılın ilk günü, yepyeni umutlarla dolsun.🎇",
                "Tüm hayallerinin gerçek olduğu bir yıl dilerim.💫",
                "Sevgi ve barış dolu bir yıl seninle olsun.🕊",
                "Yeni yıl mucizelerle gelsin.✨",
                "Hedeflerine ulaşacağın bir yıl olsun.🎯",
                "Bol kahkaha, bol mutluluk diliyorum yeni yılda.😂",
                "Yeni yıl yeni başlangıçlar demek!🔄",
                "Her yeni gün, yeni umutlar getirsin.☀",
                "2025 sana güzellikler getirsin.🌟",
                "Yeni yılda hep birlikte nice güzel anılar biriktirelim.📸",
                "Dileklerinin kabul olduğu bir yıl olsun.🎁",
                "Yeni yılın kutlu olsun!🥳"));
        messagesMap.put("Teşekkür", Arrays.asList("Teşekkür ederim!🙏",
                "Yardımın için minnettarım.💖",
                "Desteklerin benim için çok değerli.🤗",
                "İyi ki varsın, teşekkür ederim.✨",
                "Desteğin olmasaydı başaramazdım.🙌",
                "İçten teşekkürlerimi sunarım.💞",
                "Sana minnettarım.🤲 ",
                "Zaman ayırdığın için teşekkür ederim.⏳",
                "Her şey için çok teşekkürler.😊",
                "Gönülden teşekkür ederim.❤",
                "Yardımın hayatımı kolaylaştırdı.🌟",
                "İlgin için teşekkürler.💬",
                "Ne kadar teşekkür etsem az.🙇‍♀",
                "Beni yalnız bırakmadığın için sağ ol.🤝",
                "Desteğini asla unutmayacağım.💫"));
        messagesMap.put("Genel", Arrays.asList("Her şey gönlünce olsun.✨",
                "Bugün senin için güzel geçsin!🌅",
                "Hayat kısa, gülümsemeyi unutma!😃",
                "Kendine iyi bak.💖",
                "İyi dileklerim seninle.🌸",
                "Şans seninle olsun.🍀",
                "Dilerim her şey yolunda gider.☀",
                "Güzel haberlerini bekliyorum.📩",
                "Olumlu düşün, güzel yaşa.💭",
                "Ne olursa olsun gülümse!😊",
                "Umarım her şey planladığın gibi olur.🎯",
                "Zor günler geçecek, sabret.⏳",
                "Mutluluk seninle olsun.💫",
                "İç huzurun daim olsun.🕊",
                "İyi kalpli insanların yolu açıktır.💙"));
    }

    public static List<String> getMessagesByCategory(String category) {
        return messagesMap.getOrDefault(category, List.of("Bu kategori için mesaj bulunamadı."));
    }
}